// Code generated by sqlc. DO NOT EDIT.
// source: quote.sql

package db

import (
	"context"
)

const getQuote = `-- name: GetQuote :one
SELECT id, author, quote FROM quotes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetQuote(ctx context.Context, id int64) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getQuote, id)
	var i Quote
	err := row.Scan(&i.ID, &i.Author, &i.Quote)
	return i, err
}

const getQuoteRows = `-- name: GetQuoteRows :one
SELECT COUNT(*)
FROM quotes
`

func (q *Queries) GetQuoteRows(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getQuoteRows)
	var count int64
	err := row.Scan(&count)
	return count, err
}
